/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarie;

import java.awt.Color;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import static librarie.Meniu.niceID;

/**
 *
 * @author camel
 */
public class Profil extends javax.swing.JFrame {

    /**
     * Creates new form Profil
     */
    
    static String cuteID=Meniu.niceID;
    static String nm1=Meniu.nm;
    static String pr1=Meniu.pr;
    static String cn1=Meniu.cn;
    static String tl1=Meniu.tl;
    
    public Profil() {
        initComponents();
        ProfilIDLabel.setText("ID: "+ cuteID);  
        ProfilTerminalLabel.setText("CNP: "+cn1);
        numeA.setText(nm1);
        numeA.addKeyListener(new KeyAdapter() {
            public void keyPressed(KeyEvent ke) {
                String value = numeA.getText();
                int l = value.length();
                if ((ke.getKeyChar() >= 'A' && ke.getKeyChar() <= 'z' && l<20) || ke.getKeyChar()==8 || ke.getKeyChar()==' ') {
                    numeA.setEditable(true);
                } else {
                    numeA.setEditable(false);
                }
            }
        });
        prenA.setText(pr1);
        prenA.addKeyListener(new KeyAdapter() {
            public void keyPressed(KeyEvent ke) {
                String value = prenA.getText();
                int l = value.length();
                if ((ke.getKeyChar() >= 'A' && ke.getKeyChar() <= 'z' && l<30) || ke.getKeyChar()==8 || ke.getKeyChar()==' ') {
                    prenA.setEditable(true);
                } else {
                    prenA.setEditable(false);
                }
            }
        });
        telA.setText(tl1);
        telA.addKeyListener(new KeyAdapter() {
            public void keyPressed(KeyEvent ke) {
                String value = telA.getText();
                int l = value.length();
                if ((ke.getKeyChar() >= '0' && ke.getKeyChar() <= '9' && l<10) || ke.getKeyChar()==8 ) {
                    telA.setEditable(true);
                } else {
                    telA.setEditable(false);
                }
            }
        });
        pact.addKeyListener(new KeyAdapter() {
            public void keyPressed(KeyEvent ke) {
                String value = pact.getText();
                int l = value.length();
                if (l<20 || ke.getKeyChar()==8 ) {
                    pact.setEditable(true);
                } else {
                    pact.setEditable(false);
                }
            }
        });
        pnou.addKeyListener(new KeyAdapter() {
            public void keyPressed(KeyEvent ke) {
                String value = pnou.getText();
                int l = value.length();
                if (l<20 || ke.getKeyChar()==8 ) {
                    pnou.setEditable(true);
                } else {
                    pnou.setEditable(false);
                }
            }
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ProfilPanel = new javax.swing.JPanel();
        ProfilIDLabel = new javax.swing.JLabel();
        ProfilNumeLabel = new javax.swing.JLabel();
        ProfilPrenumeLabel = new javax.swing.JLabel();
        numeA = new javax.swing.JTextField();
        prenA = new javax.swing.JTextField();
        ProfilTelefonLabel = new javax.swing.JLabel();
        telA = new javax.swing.JTextField();
        ProfilParVecheLabel = new javax.swing.JLabel();
        pact = new javax.swing.JTextField();
        ProfilParNouaLabel = new javax.swing.JLabel();
        pnou = new javax.swing.JTextField();
        ProfilSaveButton = new javax.swing.JButton();
        ProfilTerminalLabel = new javax.swing.JLabel();
        ProfilBackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ProfilPanel.setBackground(new java.awt.Color(255, 247, 240));

        ProfilIDLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ProfilIDLabel.setText("ID:");

        ProfilNumeLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ProfilNumeLabel.setText("Nume:");

        ProfilPrenumeLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ProfilPrenumeLabel.setText("Prenume:");

        ProfilTelefonLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ProfilTelefonLabel.setText("Telefon:");

        ProfilParVecheLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ProfilParVecheLabel.setText("Parolă actuală:");

        ProfilParNouaLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ProfilParNouaLabel.setText("Parolă nouă:");

        ProfilSaveButton.setBackground(new java.awt.Color(255, 181, 198));
        ProfilSaveButton.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        ProfilSaveButton.setForeground(new java.awt.Color(102, 0, 102));
        ProfilSaveButton.setText("SALVEAZĂ");
        ProfilSaveButton.setMargin(new java.awt.Insets(5, 5, 2, 5));
        ProfilSaveButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ProfilSaveButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ProfilSaveButtonMouseExited(evt);
            }
        });
        ProfilSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProfilSaveButtonActionPerformed(evt);
            }
        });

        ProfilTerminalLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ProfilTerminalLabel.setText("jLabel1");

        ProfilBackButton.setBackground(new java.awt.Color(255, 181, 198));
        ProfilBackButton.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        ProfilBackButton.setForeground(new java.awt.Color(102, 0, 102));
        ProfilBackButton.setText("Înapoi");
        ProfilBackButton.setAlignmentX(0.5F);
        ProfilBackButton.setMargin(new java.awt.Insets(4, 14, 4, 14));
        ProfilBackButton.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        ProfilBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProfilBackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ProfilPanelLayout = new javax.swing.GroupLayout(ProfilPanel);
        ProfilPanel.setLayout(ProfilPanelLayout);
        ProfilPanelLayout.setHorizontalGroup(
            ProfilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfilPanelLayout.createSequentialGroup()
                .addGroup(ProfilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProfilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(ProfilSaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(ProfilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ProfilPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(ProfilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProfilPanelLayout.createSequentialGroup()
                                        .addComponent(ProfilPrenumeLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(prenA, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProfilPanelLayout.createSequentialGroup()
                                        .addComponent(ProfilNumeLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(numeA, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProfilPanelLayout.createSequentialGroup()
                                        .addComponent(ProfilParNouaLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(pnou, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProfilPanelLayout.createSequentialGroup()
                                        .addGroup(ProfilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(ProfilTelefonLabel)
                                            .addComponent(ProfilParVecheLabel))
                                        .addGap(20, 20, 20)
                                        .addGroup(ProfilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(pact, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(telA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProfilPanelLayout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addGroup(ProfilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ProfilIDLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                                    .addComponent(ProfilTerminalLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(ProfilPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ProfilBackButton)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        ProfilPanelLayout.setVerticalGroup(
            ProfilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfilPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ProfilBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ProfilIDLabel)
                .addGap(18, 18, 18)
                .addComponent(ProfilTerminalLabel)
                .addGap(24, 24, 24)
                .addGroup(ProfilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numeA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProfilNumeLabel))
                .addGap(18, 18, 18)
                .addGroup(ProfilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProfilPrenumeLabel)
                    .addComponent(prenA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ProfilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProfilTelefonLabel)
                    .addComponent(telA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ProfilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProfilParVecheLabel)
                    .addComponent(pact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ProfilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProfilParNouaLabel)
                    .addComponent(pnou, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(ProfilSaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ProfilPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ProfilPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ProfilSaveButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProfilSaveButtonMouseEntered
        this.ProfilSaveButton.setBackground(Color.decode("#FFCCD8"));        // TODO add your handling code here:
    }//GEN-LAST:event_ProfilSaveButtonMouseEntered

    private void ProfilSaveButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProfilSaveButtonMouseExited
        // TODO add your handling code here:
        this.ProfilSaveButton.setBackground(Color.decode("#FFB5C6"));
    }//GEN-LAST:event_ProfilSaveButtonMouseExited

    private void ProfilSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfilSaveButtonActionPerformed
        if(numeA.getText().isEmpty() || prenA.getText().isEmpty() || telA.getText().isEmpty() || pact.getText().isEmpty())
            JOptionPane.showMessageDialog(null, " Cel puțin unul din câmpurile nume, prenume, telefon \nsau parolă actuală este necompletat.", "Eroare", JOptionPane.INFORMATION_MESSAGE);
        else
        {
            String nnou=numeA.getText().toString();
            String prnou=prenA.getText().toString();
            String tnou=telA.getText().toString();
            String par=pact.getText().toString();
            if(!pnou.getText().isEmpty())
                par=pnou.getText().toString();
            try{  
                Class.forName("com.mysql.cj.jdbc.Driver");  
                Connection con=DriverManager.getConnection(  
                "jdbc:mysql://localhost:3306/librarie","root","");    
                Statement stmt=con.createStatement();  
                stmt.executeUpdate("update `angajat` set nume='"+nnou+"', prenume='"+prnou+"', telefon='"+tnou+"', parola='"+par+"' where ida="+cuteID+";");
                con.close();  
            }catch(Exception e){ System.out.println(e);}  
            JOptionPane.showMessageDialog(null, "Salvarea s-a efectuat cu succes.", "Notificare", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_ProfilSaveButtonActionPerformed

    private void ProfilBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfilBackButtonActionPerformed
        // TODO add your handling code here:
        dispose();
        new Meniu().setVisible(true);
    }//GEN-LAST:event_ProfilBackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Profil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Profil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Profil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Profil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Profil().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ProfilBackButton;
    private javax.swing.JLabel ProfilIDLabel;
    private javax.swing.JLabel ProfilNumeLabel;
    private javax.swing.JPanel ProfilPanel;
    private javax.swing.JLabel ProfilParNouaLabel;
    private javax.swing.JLabel ProfilParVecheLabel;
    private javax.swing.JLabel ProfilPrenumeLabel;
    private javax.swing.JButton ProfilSaveButton;
    private javax.swing.JLabel ProfilTelefonLabel;
    private javax.swing.JLabel ProfilTerminalLabel;
    private javax.swing.JTextField numeA;
    private javax.swing.JTextField pact;
    private javax.swing.JTextField pnou;
    private javax.swing.JTextField prenA;
    private javax.swing.JTextField telA;
    // End of variables declaration//GEN-END:variables
}
